# Generated by Django 5.1 on 2024-11-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_medico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medico',
        ),
    ]
